### ISSUE TITLE
Links to documentation are broken

### ISSUE THREAD

**Issue by khinsen** [mentat-collective/emmy#120]
The README contains several links to https://cljdoc.org/, which are all broken.

**Comment by sritchie** [comment]
Thanks @khinsen ! Good call... I'll get a jar released in the next few days, which will fix those links. These are casualties of my rename to Emmy.

**Comment by sritchie** [comment]
Okay, the library is released now as 0.30.0 https://clojars.org/org.mentat/emmy, so the links all work now. Thank you!
